services:
#  app:
##    build:
##      context: .
##      dockerfile: Dockerfile
#    container_name: ${APP_CONTAINER_NAME}
#
##    ports:
##      - "8080:8080"
#
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

#    depends_on:
#      postgres:
#        condition: service_healthy
#
#    networks:
#      - fleetOps2

  postgres:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${POSTGRES_DATA_PATH}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:${POSTGRES_DATA_PATH}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

#    networks:
#      - fleetOps2

volumes:
  postgres_data:

#networks:
#  fleetOps2:
#    external: true