{
  "type": "record",
  "name": "ProductUpdatedEvent",
  "namespace": "com.samtar.avro",

  "fields": [
    {
      "name": "productId",
      "type": "string"
    },
    {
      "name": "productName",
      "type": "string"
    },
    {
      "name": "description",
      "type": ["null", "string"],
      "default": null
    },
    {
      "name": "price",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 19,
        "scale": 2
      }
    },
    {
      "name": "quantity",
      "type": "int"
    },
    {
      "name": "categoryId",
      "type": ["null", "string"],
      "default": null
    }
  ]
}