{
  "type": "record",
  "name": "EventEnvelope",
  "namespace": "com.samtar.avro",

  "fields": [
    {
      "name": "eventId",
      "type": "string"
    },
    {
      "name": "eventType",
      "type": "string"
    },
    {
      "name": "aggregateType",
      "type": "string"
    },
    {
      "name": "aggregateId",
      "type": "string"
    },
    {
      "name": "occurredAt",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "version",
      "type": "int",
      "default": 1
    }
  ]
}